AWSTemplateFormatVersion: version date
Description: Creating the VPC
Metadata:
  template metadata

Parameters:
 VpcCIDR:
  Default: 10.0.0.0/16
  Description: Creating the cidr for vpc
  Type: String

 Subnet1CIDR:
  Default: 10.0.0.0/24
  Description: Creating the cidr for subnet 1
  Type: String

 Subnet2CIDR:
  Default: 10.0.1.0/24
  Description: Creating the cidr for subnet 2
  Type: String

 Subnetpvt3CIDR:
  Default: 10.0.2.0/24
  Description: Creating the cidr for subnet 3
  Type: String

 Subnetpvt4CIDR:
  Default: 10.0.3.0/24
  Description: Creating the cidr for subnet 4
  Type: String
   
Resources:
  set of resources

Outputs:
  set of outputs
